services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe230405180405
      POSTGRES_DB: notesync
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:qwe230405180405@db:5432/your_database

volumes:
  postgres_data:
