version: '3.8'

services:

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwe230405180405
    ports:
      - 5436:5432

  notesync:
    build: ./
    command: ./wait-for-postgres.sh db 5432 ./notesync  # Убедитесь, что это путь к вашему приложению
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwe230405180405
      - DB_HOST=db
      - DB_PORT=5432
